"""empty message

Revision ID: 65098ed091cf
Revises: 908325fa633a
Create Date: 2025-07-08 21:48:48.503580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65098ed091cf'
down_revision = '908325fa633a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
