"""empty message

Revision ID: 908325fa633a
Revises: d67d3b093ca6
Create Date: 2025-07-08 21:39:12.900013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908325fa633a'
down_revision = 'd67d3b093ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planet_favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planet_favorites_pkey')
    )
    op.drop_table('planets_favorites')
    # ### end Alembic commands ###
